name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      platform: aws
      region: us-west-2
      account: 123456789012

      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    steps:
      - name: "Display message"
        run: echo "Hello, World!"

      - name: "Display environment variables"
        run: |
          echo "Platform: ${{env.platform}} "
          echo "Region: ${{env.region}} "
          echo "Account: ${{env.account}}"

          echo "Username: ${{env.username}}"
          echo "Password: ${{env.password}}"

      - name: "Displaying default variables"
        run: |
          echo "Event: ${{toJson(github.event)}}"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
